/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.print.attribute.standard.JobPriority;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class FormVehiculosPoli extends javax.swing.JFrame {

    /**
     * Creates new form FormVehiculosPoli
     */
    public FormVehiculosPoli() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        panelAuto.setVisible(false);
        panelCamion.setVisible(false);
    }
    
    public void alternarPaneles(){
        
        if(cboTipoVehiculo.getSelectedIndex() == 0){
            panelAuto.setVisible(false);
            panelCamion.setVisible(false);
        }else{
        boolean seleccion = cboTipoVehiculo.getSelectedItem().equals("Auto");
        panelAuto.setVisible(seleccion);
        panelCamion.setVisible(!seleccion);
        }
    }
    
    public void limpiarCampos(){
        txtMarca.setText("");
        txtAnio.setText("");
        txtCombustible.setText("");
        txtPrecioBase.setText("");
        txtModelo.setText("");
        txtCostoMantenimiento.setText("");
        txtDescuento.setText("");
        txtToneladas.setText("");
        txtPuertas.setText("");
        txtToneladas.setText("");
        txtCostoMantenimiento.setText("");
        txtEjes.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboTipoVehiculo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioBase = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        panelCamion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtToneladas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEjes = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCostoMantenimiento = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultadoCamion = new javax.swing.JTextArea();
        chk_remolque = new javax.swing.JCheckBox();
        panelAuto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtPuertas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCombustible = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        chk_aireAcondicionado = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultadoAuto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(255, 226, 197));
        Titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 36)); // NOI18N
        jLabel1.setText("Estacionamiento Autos");
        Titulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 510, -1));

        Fondo.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 110));

        cboTipoVehiculo.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 1, 18)); // NOI18N
        cboTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo Vehiculo", "Auto", "Camion" }));
        cboTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoVehiculoActionPerformed(evt);
            }
        });
        Fondo.add(cboTipoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 310, -1));

        jLabel2.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        jLabel2.setText("PrecioBase");
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        jLabel3.setText("Marca");
        Fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        jLabel4.setText("Modelo");
        Fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        jLabel5.setText("Año");
        Fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));
        Fondo.add(txtPrecioBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 130, 30));

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        Fondo.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 30));

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        Fondo.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 100, 30));
        Fondo.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 130, 30));

        btnLimpiar.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        Fondo.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 110, -1));

        btnIngresar.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        Fondo.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        panelCamion.setBackground(new java.awt.Color(255, 255, 255));
        panelCamion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCamion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        jLabel9.setText("Capacidad Toneladas");
        panelCamion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txtToneladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToneladasActionPerformed(evt);
            }
        });
        panelCamion.add(txtToneladas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 140, -1));

        jLabel10.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        jLabel10.setText("Ejes");
        panelCamion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));
        panelCamion.add(txtEjes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, -1));

        jLabel11.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        jLabel11.setText("Costo Mantenimiento");
        panelCamion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        panelCamion.add(txtCostoMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 140, -1));

        txtResultadoCamion.setColumns(20);
        txtResultadoCamion.setLineWrap(true);
        txtResultadoCamion.setRows(5);
        jScrollPane2.setViewportView(txtResultadoCamion);

        panelCamion.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 350, 520));

        chk_remolque.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        chk_remolque.setText("Remolque");
        panelCamion.add(chk_remolque, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        Fondo.add(panelCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 670, 600));

        panelAuto.setBackground(new java.awt.Color(255, 255, 255));
        panelAuto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelAuto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        jLabel6.setText("Puertas:");
        panelAuto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        txtPuertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuertasActionPerformed(evt);
            }
        });
        panelAuto.add(txtPuertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 140, -1));

        jLabel7.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        jLabel7.setText("Tipo Combustible:");
        panelAuto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        panelAuto.add(txtCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 140, -1));

        jLabel8.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        jLabel8.setText("Descuento:");
        panelAuto.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));
        panelAuto.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 140, -1));

        chk_aireAcondicionado.setFont(new java.awt.Font("CaskaydiaMono NF SemiBold", 0, 18)); // NOI18N
        chk_aireAcondicionado.setText("Aire Acondicionado");
        panelAuto.add(chk_aireAcondicionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        txtResultadoAuto.setColumns(20);
        txtResultadoAuto.setLineWrap(true);
        txtResultadoAuto.setRows(5);
        jScrollPane3.setViewportView(txtResultadoAuto);

        panelAuto.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 350, 520));

        Fondo.add(panelAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 670, 600));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtPuertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuertasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuertasActionPerformed

    private void txtToneladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToneladasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToneladasActionPerformed

    private void cboTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoVehiculoActionPerformed
        alternarPaneles();

    }//GEN-LAST:event_cboTipoVehiculoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if(txtMarca.getText().trim().isEmpty() || txtModelo.getText().trim().isEmpty() || txtAnio.getText().trim().isEmpty() || txtPrecioBase.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Error: Los Campos No Pueden Estar Vacios", "Advertencia", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String marca = txtMarca.getText();
        String modelo = txtModelo.getText();
        int anio = Integer.parseInt(txtAnio.getText());
        double precioBase = Double.parseDouble(txtPrecioBase.getText());
        
        if(precioBase < 0){
            JOptionPane.showMessageDialog(this, "Error: No Puede Ingresar Precios Menores a 0", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String tipoVehiculo = (String) cboTipoVehiculo.getSelectedItem();
        if(("Auto").equals(tipoVehiculo)){
            
            int puertas = Integer.parseInt(txtPuertas.getText());
            boolean aireAcondicionado = chk_aireAcondicionado.isSelected();
            
            if(chk_aireAcondicionado.isSelected()){
                JOptionPane.showMessageDialog(this, "El Auto Tiene Aire Acondicionado Por Lo Cual Se Aumentara $800 al Precio" + "Informacion"+ JOptionPane.INFORMATION_MESSAGE);
            }
            
            double descuento = Double.parseDouble(txtDescuento.getText());
            String tipoCombustible = txtCombustible.getText();
            
            Auto auto = new Auto();
            
            auto.setAnio(anio);
            auto.setMarca(marca);
            auto.setModelo(modelo);
            auto.setPrecioBase(precioBase);
            
            auto.setPuertas(puertas);
            auto.setAireAcondicionado(aireAcondicionado);
            auto.setDescuento(descuento);
            auto.setTipoCombustible(tipoCombustible);
            
            
            auto.calcularTotal();
            
            txtResultadoAuto.append(auto.mostrarInfo());
        }
        
        if(("Camion").equals(tipoVehiculo)){
            
            int capacidadToneladas = Integer.parseInt(txtToneladas.getText());
            int ejes = Integer.parseInt(txtEjes.getText());
            double costoMantenimiento = Double.parseDouble(txtCostoMantenimiento.getText());
            
            boolean remolque = chk_remolque.isSelected();
            
            if(chk_remolque.isSelected()){
                JOptionPane.showMessageDialog(this, "El Camion Tiene Remolque Por Lo Cual Se Aumentara $1200 al Total" + "Informacion"+ JOptionPane.INFORMATION_MESSAGE);
            }
            
            Camion camion = new Camion();
            
            camion.setAnio(anio);
            camion.setMarca(marca);
            camion.setModelo(modelo);
            camion.setPrecioBase(precioBase);
            
            camion.setCapacidadToneladas(capacidadToneladas);
            camion.setEjes(ejes);
            camion.setCostoMantenimiento(costoMantenimiento);
            camion.setRemolque(remolque);
            
            camion.calcularTotal();
            
            txtResultadoCamion.append(camion.mostrarInfo());
            
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "Recuerde que todo el Sistema se Limpiara", "Limpiar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(opcion == JOptionPane.YES_OPTION){
            limpiarCampos();
        }
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVehiculosPoli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVehiculosPoli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVehiculosPoli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVehiculosPoli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVehiculosPoli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Titulo;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboTipoVehiculo;
    private javax.swing.JCheckBox chk_aireAcondicionado;
    private javax.swing.JCheckBox chk_remolque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelAuto;
    private javax.swing.JPanel panelCamion;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtCombustible;
    private javax.swing.JTextField txtCostoMantenimiento;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtEjes;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecioBase;
    private javax.swing.JTextField txtPuertas;
    private javax.swing.JTextArea txtResultadoAuto;
    private javax.swing.JTextArea txtResultadoCamion;
    private javax.swing.JTextField txtToneladas;
    // End of variables declaration//GEN-END:variables
}
